### ISSUE TITLE
include wildfly example

### ISSUE THREAD

**Issue by erickdeoliveiraleal** [ttddyy/datasource-proxy-examples#1]
include wildfly example

**Comment by ttddyy** [comment]
I personally haven't had chance to use wildfly. 
Appreciate if somebody make a PR for that.

**Comment by erickdeoliveiraleal** [comment]
Why did you close this? I can't find WildFly example anywhere in Google.

**Comment by oleg-vyalyh** [comment]
Hi. I also would be appreciate if you add even a hint how to use it with the jboss/wildfly.
The initial DataSource is described with the "*-ds.xml" file (but may be set in the server standalone/domain xml configurations). But the the difficulty is due to the fact that it is not clear how to specify specific DataSource type (or may be some special DataSourceProxy factory) which should be used instead of default one.

**Comment by cljk** [comment]
I came up to this issue since I wanted to use datasource proxy in wildlfy on my own.... and had a small look into it.

Since it doesn´t include (?) a JDBC driver but has to be setup programmatically as I see in the examples, I think the datasource proxy cannot be enabled as datasource in wildfly JNDI. So it can´t be used in wildlfy :-/
